[package]
name = "quvyta"
version = "0.1.2"
edition = "2024"
rust-version = "1.95"
license = "MIT"
description = "Introduces the Quvyta family of terminal applications and how to install each one (beta)"
repository = "https://github.com/quvyta/quvyta"
readme = "README.md"
keywords = ["tui", "terminal", "quvyta"]
categories = ["command-line-utilities"]
include = ["src/**", "assets/**", "Cargo.toml", "Cargo.lock", "README.md", "LICENSE"]

[dependencies]
quvyta-framework = "0.1.3"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
cast_lossless = "deny"
needless_pass_by_value = "deny"
redundant_closure_for_method_calls = "deny"
semicolon_if_nothing_returned = "deny"
uninlined_format_args = "deny"
